name: test aws actions

on:
  pull_request:
  push:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
    - name: Setup ROS2
      uses: ros-tooling/setup-ros2@0.0.12
    # - name: Extra Mac Dependencies
    #   if: contains(matrix.os, 'macos-latest')
    #   run: |
    #     pip3 install lxml
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.0.13
      with:
        package-name: |
          confbot_bringup
          confbot_description
          confbot_driver
          confbot_msgs
          confbot_security
          confbot_sensors
          confbot_simulation
          confbot_tools

    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()
